### ISSUE TITLE
Exception when trying to run the container

### ISSUE THREAD

**Issue by telometto** [MitchTalmadge/shreddit-dockerized#2]
For some odd reason it seems that an exception is caused because of `Max retres`. I don't know if it is caused by the app itself or if it is due to the recent API changes at Reddit.
```py
During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/local/bin/shreddit", line 8, in <module>

    sys.exit(main())

  File "/usr/local/lib/python3.8/site-packages/shreddit/app.py", line 44, in main

    shredder = Shredder(default_config, args.user)

  File "/usr/local/lib/python3.8/site-packages/shreddit/shredder.py", line 28, in __init__

    self._connect()

  File "/usr/local/lib/python3.8/site-packages/shreddit/shredder.py", line 81, in _connect

    self._logger.info("Logged in as {user}.".format(user=self._r.user.me()))

  File "/usr/local/lib/python3.8/site-packages/praw/models/user.py", line 133, in me

    user_data = self._reddit.get(API_PATH["me"])

  File "/usr/local/lib/python3.8/site-packages/praw/reddit.py", line 490, in get

    return self._objectify_request(method="GET", params=params, path=path)

  File "/usr/local/lib/python3.8/site-packages/praw/reddit.py", line 573, in _objectify_request

    self.request(

  File "/usr/local/lib/python3.8/site-packages/praw/reddit.py", line 726, in request

    return self._core.request(

  File "/usr/local/lib/python3.8/site-packages/prawcore/sessions.py", line 332, in request

    return self._request_with_retries(

  File "/usr/local/lib/python3.8/site-packages/prawcore/sessions.py", line 252, in _request_with_retries

    return self._do_retry(

  File "/usr/local/lib/python3.8/site-packages/prawcore/sessions.py", line 162, in _do_retry

    return self._request_with_retries(

  File "/usr/local/lib/python3.8/site-packages/prawcore/sessions.py", line 252, in _request_with_retries

    return self._do_retry(

  File "/usr/local/lib/python3.8/site-packages/prawcore/sessions.py", line 162, in _do_retry

    return self._request_with_retries(

  File "/usr/local/lib/python3.8/site-packages/prawcore/sessions.py", line 227, in _request_with_retries

    response, saved_exception = self._make_request(

  File "/usr/local/lib/python3.8/site-packages/prawcore/sessions.py", line 185, in _make_request

    response = self._rate_limiter.call(

  File "/usr/local/lib/python3.8/site-packages/prawcore/rate_limit.py", line 36, in call

    response = request_function(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/prawcore/requestor.py", line 55, in request

    raise RequestException(exc, args, kwargs)

prawcore.exceptions.RequestException: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /api/v1/me?raw_json=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f688d43d4f0>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by MitchTalmadge** [comment]
That's interesting, the error makes it sound like the container has no internet or something. Or maybe Reddit removed whatever url it has been trying to talk to. If you know how to open a terminal in the container, maybe try running curl or wget on Reddit.com and see if anything comes back, to see if internet is working in the container.

**Comment by telometto** [comment]
You want to know what's even more interesting? That all of the sudden I spun up the container again and it just works... 🙄

Oh, well; nothing better than things starting to function by themselves again and thus get spared the troubleshooting 🤷‍♂️😆

**Comment by MitchTalmadge** [comment]
Oh, well how about that! Glad to hear it's working! :)
